export const weekDays = [
  { label: 'Mon', date: '2' },
  { label: 'Tue', date: '3' },
  { label: 'Wed', date: '4' },
  { label: 'Thu', date: '5' },
  { label: 'Fri', date: '6' },
  { label: 'Sat', date: '7' },
  { label: 'Sun', date: '8' },
];
export const totalHours = ['0:00','1:00','2:00','3:00','4:00','5:00','6:00','7:00','8:00','9:00','10:00','11:00','12:00',
                          '13:00','14:00','15:00','16:00','17:00','18:00','19:00','20:00','21:00','22:00','23:00'];
export const currentWeekData = {
  dateFrom: 'December 02, 2019 00:00:00',
  dateTo: 'December 08, 2019 23:00:00',
  dateFormatted: 'December 2019',
  events: {
    '2-12-2019': [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '1', name: 'Morning Coffee', label: 0, timeSpan: 1 },
      {},
      { id: '2', name: 'Interview with company', label: 10, hour: 10, timeSpan: 3 },
      {},
      {},
      {},
      {},
      { id: '3', name: 'Buy birthday gift', label: 3, timeSpan: 1 },
      { id: '4', name: 'Gym', label: 0, timeSpan: 2 },
      {},
      {},
      {},
      {},
    ],
    '3-12-2019': [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '5', name: 'Morning Coffee', label: 0, timeSpan: 1 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '6', name: 'Gym', label: 0, timeSpan: 2 },
      {},
      {},
      {},
      {},
    ],
    '4-12-2019': [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '7', name: 'Morning Coffee', label: 0, timeSpan: 1 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '8', name: 'Gym', label: 0, timeSpan: 2 },
      {},
      {},
      {},
      {},
    ],
    '5-12-2019': [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '9', name: 'Morning Coffee', label: 0, timeSpan: 1 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '10', name: 'Gym', label: 0, timeSpan: 2 },
      {},
      {},
      {},
      {},
    ],
    '6-12-2019': [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '11', name: 'Morning Coffee', label: 0, timeSpan: 1 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '12', name: 'Gym', label: 0, timeSpan: 3 },
      {},
      {},
      {},
      {},
    ],
    '7-12-2019': [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      { id: '13', name: 'Morning Coffee', label: 0, timeSpan: 1 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    '8-12-2019': [
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
  },
};
